### ISSUE TITLE
Show dropdown of installed plugins/themes instead of requiring user to enter slug

### ISSUE THREAD

**Issue by westonruter** [afragen/skip-updates#2]
The current UI for adding a plugin/theme looks as follows:

> ![image](https://user-images.githubusercontent.com/134745/110980309-91985500-831a-11eb-8cfb-00bf32ffa7b8.png)

This is not super user-friendly because it requires the user to look up the slug. What if instead there was one dropdown that included both the themes and the plugins in option groups?

> ![image](https://user-images.githubusercontent.com/134745/110980700-ffdd1780-831a-11eb-978a-8706736f32b1.png)

**Comment by afragen** [comment]
That look very nice. Can't wait for the PR 👍
